.catalog:
  name: "Bind9 DNS"
  version: "v0.2-updiversity"
  description: "Domain Name Server powered by Bind9"
  minimum_rancher_version: v1.2.0-pre4-rc1
  questions:
    - variable: "BIND9_IP"
      label: "Bind9 ip"
      description: "public IP of the DNS"
      type: "string"
      required: false
    - variable: "BIND9_ROOTDOMAIN"
      label: "The root domain to manage in bind9"
      description: "This root domain will be managed by the Bind9 server. Updates and axfr requests will be made on this domain"
      type: "string"
      required: true
    - variable: "BIND9_KEYNAME"
      label: "Bind9 TSIG Keyname"
      description: "The TSIG keyname"
      type: "string"
      required: true
    - variable: "BIND9_KEY"
      label: "Bind9 TSIG Key (base64 encoded)"
      description: "The TSIG key. Must be base64 encoded"
      type: "string"
      required: true
    - variable: "BIND9_KEY_ALGORITHM"
      label: "Bind9 TSIG Key Algorithm"
      description: "The key algo - examples : hmac-md5, hmac-sha1, hmac-sha256, hmac-sha512"
      type: "string"
      required: false
    - variable: "BIND9_PORT"
      label: "Bind9 port"
      description: "Bind9 port to expose on host. Will be used to bind both TCP and UDP"
      type: "string"
      default: 53
      required: true
    - variable: "BIND9_FORWARDERS"
      label: "Bind9 dns forwarders"
      description: "The DNS forwarders"
      type: "string"
      default: 8.8.8.8;8.8.4.4;
      required: true
    - variable: "BIND9_IPV4ONLY"
      label: "Bind9 IPV4 Only"
      description: "set bind9 to support only IPV4"
      type: "string"
      required: false
    - variable: "BIND9_QUERY_CACHE_ACCEPT"
      label: "Bind9 Query Cache"
      description: "set IP to allow in allow-query-cache"
      type: "string"
      default: 127.0.0.1;
      required: true
    - variable: "BIND9_RECURSION_ACCEPT"
      label: "Bind9 Recursion"
      description: "set IP to allow in allow-recursion"
      type: "string"
      default: 127.0.0.1;
      required: true
    - variable: "BIND9_STATIC_ENTRIES"
      label: "Bind9 Static Entries"
      description: "The multiline static entries for your zone"
      type: "string"
      required: false

bind9:
  scale: 1
  health_check:
    port: ${BIND9_PORT}
    interval: 2000
    initializing_timeout: 20000
    unhealthy_threshold: 3
    strategy: recreate
    healthy_threshold: 2
    response_timeout: 2000
