name: OpenVPN
description: |
  una herramienta de conectividad basada en software libre: SSL (Secure Sockets Layer), VPN Virtual Private Network (red virtual privada)!
version: v0.1-updiversity
category: Proyectos
